#!/bin/bash

export BINDIR=/usr/local/bin

export BITSDIR=$HOME/download

# VMware Customer Connect Download Account
export VMD_USER='<username>'
export VMD_PASS='<password>'

# CLI Tools version

export VMDRELEASE=0.2.0