#!/bin/bash

export BINDIR=/usr/local/bin

export BITSDIR=$HOME/Downloads

# VMware Customer Connect Download Account
# get it from https://customerconnect.vmware.com/
export VCC_USER='<username>'
export VCC_PASS='<password>'

#VMware Market place api token
#get it from https://marketplace.cloud.vmware.com/
export CSP_API_TOKEN='<insert-csp-token-here>'

#VMware Tanzu network API refresh token
#get it from https://network.pivotal.io/
export APIREFRESHTOKEN='<insert-csp-token-here>'


# CLI Tools version
export VMDRELEASE=0.2.0
export MKPCLIRELEASE=0.14.0
export PIVNETRELEASE=v3.0.1
export VCCRELEASE=v1.1.3
#OVAs
export HAPROXYRELEASE=0.2.0