#!/bin/bash

export BINDIR=/usr/local/bin

export BITSDIR=$HOME/Downloads

# VMware Customer Connect Download Account
export VMD_USER='<username>'
export VMD_PASS='<password>'

#VMware Market place api token
export CSP_API_TOKEN='<insert-csp-token-here>'

# CLI Tools version
export VMDRELEASE=0.2.0
export MKPCLIRELEASE=0.14.0

#OVAs
export HAPROXYRELEASE=0.2.0